{
 "title": "4 Sinais de Ouro",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Golden Signals (GLOBAL)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency p95 (Global)",
   "type": "stat",
   "description": "p95 agregado de todas as requisições HTTP",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_server_duration_bucket[$__range])\n  )\n)\n\n",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Traffic – Global (RPS)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_server_duration_count[$__range])\n)\n",
     "legendFormat": "{{job}} – requests"
    }
   ]
  },
  {
   "title": "Error Rate (Global)",
   "type": "stat",
   "description": "Taxa de erro agregada baseada em traces",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(traces_service_graph_request_failed_total[5m]))\n/\nsum(rate(traces_service_graph_request_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation – Global",
   "type": "gauge",
   "description": "O número total de requisições HTTP que estão sendo processadas ao mesmo tempo no sistema, neste exato momento.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Golden Signals (Por job)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (job, le) (\r\n    rate(http_server_duration_bucket[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (job) (\r\n  rate(http_server_duration_count[5m])\r\n)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (server) (\r\n  rate(traces_service_graph_request_failed_total{server!=\"unknown\"}[5m])\r\n)\r\n/\r\nsum by (server) (\r\n  rate(traces_service_graph_request_total{server!=\"unknown\"}[5m])\r\n)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (job) (\r\n  http_server_active_requests\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}