{
 "title": "4 Sinais de Ouro",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(http_server_duration_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latência p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, job)(\n    rate(\n      http_server_duration_bucket{job=~\"desafio/$job\"}[$__range]\n    )\n  )\n)\n",
     "legendFormat": "{{job}} – p95"
    }
   ]
  },
  {
   "title": "Tráfego (requests no período)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job)(\n  rate(\n    http_server_duration_count{job=~\"desafio/($job)\"}[$__range]\n  )\n)\n",
     "legendFormat": "{{job}} – requests"
    }
   ]
  },
  {
   "title": "Erro (%) no período",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by (job)(\n  increase(\n    http_server_duration_count{\n      job=~\"desafio/$job\",\n      http_status_code=~\"5..\"\n    }[$__range]\n  )\n)\n/\nsum by (job)(\n  increase(\n    http_server_duration_count{job=~\"desafio/$job\"}[$__range]\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturação (requests ativos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job)(\n  http_server_active_requests{job=~\"desafio/$job\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de dependências (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job)(\n  increase(\n    http_server_duration_count{\n      job=~\"desafio/$job\",\n      http_status_code=~\"5..\"\n    }[$__range]\n  )\n)\n",
     "legendFormat": "{{job}} – errors"
    }
   ]
  },
  {
   "title": "Dependências – volume outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job)(\n  increase(\n    http_client_duration_count{job=~\"desafio/$job\"}[$__range]\n  )\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}