{
 "title": "RED",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(http_server_duration_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_duration_count{\r\n      job=~\"desafio/$job\"\r\n    }[$__range]\r\n  )\r\n)",
     "legendFormat": "HTTP server request rate (total)"
    }
   ]
  },
  {
   "title": "Global Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(traces_service_graph_request_failed_total[$__range]))\r\n/\r\nsum(rate(traces_service_graph_request_total[$__range]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Percentiles (SLO/SLA)",
   "type": "timeseries",
   "description": "Se o usuário percebe a lentidao",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (rate(http_server_duration_bucket[$__range]))\r\n)\r\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (rate(http_server_duration_bucket[5m]))\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (rate(http_server_duration_bucket[5m]))\r\n)\r\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Duration histogram (s)",
   "type": "histogram",
   "description": "Como está a distribuição de latência neste período",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(\r\n    http_server_duration_bucket[$__range]\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "description": "Verifica a latencia ao longo do tepo",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  rate(http_server_duration_bucket[$__range])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}